# Generated by Django 6.0.1 on 2026-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_paidpost_unique_together_paidpost_phone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paidpost',
            unique_together={('phone', 'post')},
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='paidpost',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.RemoveField(
            model_name='paidpost',
            name='user',
        ),
    ]
