# Generated by Django 6.0.1 on 2026-01-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_paymenttransaction_mpesa_receipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField()),
                ('secret_key', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='blog.post')),
            ],
        ),
    ]
