# Generated by Django 6.0.1 on 2026-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_feedback_post_remove_feedback_secret_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='feedback',
            name='secret_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
