# Generated by Django 6.0.1 on 2026-01-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_feedback_is_featured_feedback_secret_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='secret_key',
        ),
    ]
