# Generated by Django 6.0.1 on 2026-01-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_paymenttransaction_refunded_at_post_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meta_keywords',
        ),
    ]
