# Generated by Django 6.0.1 on 2026-01-21 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_adminauditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action'], name='blog_admina_action_12cbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['timestamp'], name='blog_admina_timesta_0f8738_idx'),
        ),
    ]
