# Generated by Django 6.0.1 on 2026-01-30 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_paymenttransaction_user_alter_postaccess_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.googleuser'),
        ),
        migrations.AlterField(
            model_name='postaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.googleuser'),
        ),
    ]
