# Generated by Django 6.0.5 on 2026-06-01 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_feedback_secret_key_post_is_published_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postaccess",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="checkout_request_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="mpesa_receipt",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="postaccess",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique_post_access"
            ),
        ),
    ]
