# Generated by Django 6.0.5 on 2026-06-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0025_postcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="custom_author",
            field=models.CharField(
                blank=True,
                help_text="Optional: Use this to override the default admin author name for guest writers",
                max_length=150,
                null=True,
            ),
        ),
    ]
