# Generated by Django 6.0.5 on 2026-06-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_post_custom_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="part_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The sequence number for this specific post (e.g., 1, 2, 3)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="series_name",
            field=models.CharField(
                blank=True,
                help_text="If this is part of a multi-part story, type the series name here (e.g., 'The Genesis Protocol')",
                max_length=150,
                null=True,
            ),
        ),
    ]
